title: Milton Waddams&rsquo;s resume
footnote: © 2023 Me; I could set the building on...
  
baseurl: 
url: ""

social_links:
  - { platform: email,  url: "&#109;ailto&#58;mwaddams&#64;initech&#46;com", title: "mwaddams&#64;initech&#46;com" }
  - { platform: linkedin, url: "https://www.linkedin.com/in/miltonwaddams/", title: "LinkedIn profile" }
github_repository:
  title: github.com/miltonwaddams/resume
  url: https://github.com/miltonwaddams/resume

collections_dir: content
collections:
  clients:
    output: false
  skills:
    output: false
  experience:
    output: false
  experiencePrevious:
    output: false
  education:
    output: false
